---
version: '3.5'

services:

  jenkinsfile-loader:
    build: .
    environment:
      JENKINS_URL: 'http://localhost:8080'
      JENKINSFILES_DIR: '/usr/local/src/jenkinsfiles'
      DEBUG: 'true'
    volumes:
    - type: bind
      source: ${PWD}/src
      target: /usr/local/src/src
      read_only: true
    - type: bind
      source: ${PWD}/jenkinsfiles
      target: /usr/local/src/jenkinsfiles
      read_only: true
    network_mode: host
    tty: true

